server:
  port: 8080

spring:
  # 默认时区
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  profiles:
    active: ${ENV:dev}   # 获取环境变量，让程序去加载特定的 application-{ENV}文件
  datasource:
    url: jdbc:mysql://${MYSQL_URL:127.0.0.1:3306/${MYSQL_DATABASE:project}}?characterEncoding=utf-8&useSSL=false
    # 使用druid数据源
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASS:root}
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql8 及其之后的版本驱动
#    driver-class-name: com.mysql.jdbc.Driver # mysql8 之前的版本驱动
    type: com.alibaba.druid.pool.DruidDataSource
  flyway:
    validate-on-migrate: false
    locations: classpath:db/migration
mybatis:
  mapper-locations: classpath:mapper/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: org.octans.project.entity.entity  # 注意：对应实体类的路径